"""Constants used by the code
"""
#       ____                _              _       
#      / ___|___  _ __  ___| |_ __ _ _ __ | |_ ___ 
#     | |   / _ \| '_ \/ __| __/ _` | '_ \| __/ __|
#     | |__| (_) | | | \__ \ || (_| | | | | |_\__ \
#      \____\___/|_| |_|___/\__\__,_|_| |_|\__|___/
#                                                  
#

TERMINAL_PORT = 9999
TERMINAL_HOST = "127.0.0.1"

# SLEEP PERIOD in seconds
# This time is the time waited by the robot to sleep between tasks 
# Keep in mind this will index the controler speed and reflect RT performances as F = 1 / T
ROBOT_SLEEP_TIME = 0.1 # <- Dont go higher than 0.1s or 10 hz

DATA_DIR = "data"
AUTOGEN_DIR = "data/autogenerated"
TEST_FILE = "test.yaml"
PROCESS_FILE = "data.yaml"

# This is used for the modbus
MOTS = {"Current_Action":(130,"R"),
        "Next_Action":(131,"W"),
        "isEmergencyStopped":(262,"R"),
        "state":(258,"R")}

LOGO = r"""#      _   _ ____  __  __           _ _                         _____ _   _ ___ 
#     | | | |  _ \|  \/  | ___   __| | |__  _   _ ___          |_   _| | | |_ _|
#     | | | | |_) | |\/| |/ _ \ / _` | '_ \| | | / __|  _____    | | | | | || | 
#     | |_| |  _ <| |  | | (_) | (_| | |_) | |_| \__ \ |_____|   | | | |_| || | 
#      \___/|_| \_\_|  |_|\___/ \__,_|_.__/ \__,_|___/           |_|  \___/|___|
#                                                                               
# --------------------------------------------------------------------------------- """

#REAL Robot IP
UR5_IP = "192.168.1.10"
#Container name if running locally
CONTAINER = "ursim"

MODE= "AUTO" #AUTO = run process MANUAL = you add tasks

AUTO_LOAD = True # Does the but must auto load the process file from the loaded upr code ?