"""Constants used by the code
"""
#       ____                _              _       
#      / ___|___  _ __  ___| |_ __ _ _ __ | |_ ___ 
#     | |   / _ \| '_ \/ __| __/ _` | '_ \| __/ __|
#     | |__| (_) | | | \__ \ || (_| | | | | |_\__ \
#      \____\___/|_| |_|___/\__\__,_|_| |_|\__|___/
#                                                  
#

class Settings():
    """This class hold the settings
    """

    # -------------- Execution Settings ---------- #
    # MODE defines if the bot autorun the sequence or if you have to input tasks
    # AUTO will cycle the process ordering
    # MANUAL will require to add task via the TUI 
    # Default AUTO 
    MODE: str = "AUTO"
    # AUTO_LOAD whill try to load the process file using the loaded urp code. Default True
    # IF it doesnt exist it fallback to TEST_FILE and PROCESS_FILE
    AUTO_LOAD: bool = True 

    # -------------- TUI Settings ---------- #
    # TERMINAL_PORT the port used by the TUI. Default 9999
    TERMINAL_PORT: int = 9999 
    # TERMINAL_HOST the ip used by the TUI. Default 127.0.0.1
    TERMINAL_HOST: str = "127.0.0.1"

    # -------------- Robot Settings ----------- #
    # ROBOT_SLEEP_TIME the time sleept by the bot when doing nothing. Default 0.1
    # Keep in mind this will index the controler speed and reflect RT performances as F = 1 / T
    # MUST BE THE SAME AS THE ONE ON THE BOT
    # Dong go higher than 10hz
    ROBOT_SLEEP_TIME: float = 0.1 
    # UR5_IP Robot IP. Default 192.168.1.10
    UR5_IP: str = "192.168.1.10"
    # Container name if running locally. Default ursim
    CONTAINER: str = "ursim"

    # -------------- File locations ----------- #
    # DATA_DIR location of YAML files. Default data
    DATA_DIR: str = "data"
    # AUTOGEN_DIR location of saved task times. Default data/autogenerated
    AUTOGEN_DIR: str = "data/autogenerated"
    # TEST_FILE location of the file loaded if running in container and unable to load active programe file. Default test.yaml
    TEST_FILE: str = "test.yaml"
    # PROCESS_FILE location of the file loaded if running on real robot and unable to load active programe file. Default data.yaml
    PROCESS_FILE: str = "data.yaml"

    # -------------- Modbus Settings ----------- #
    # MOTS this store readable words and their associated value
    # Default
    # MOTS = {"Current_Action":(130,"R"),       <--- Current ongoing task
    #     "Next_Action":(131,"W"),              <--- Next scheduled task
    #     "isEmergencyStopped":(262,"R"),       <--- Emergency check
    #     "state":(258,"R")}                    <--- Bot state
    MOTS: dict[tuple] = {"Current_Action":(130,"R"),
            "Next_Action":(131,"W"),
            "isEmergencyStopped":(262,"R"),
            "state":(258,"R")}
    
    # -------------- Misc Settings ----------- #
    # LOGO store the app logo
    # Default
    # LOGO = r"""#      _   _ ____  __  __           _ _                         _____ _   _ ___ 
    #     | | | |  _ \|  \/  | ___   __| | |__  _   _ ___          |_   _| | | |_ _|
    #     | | | | |_) | |\/| |/ _ \ / _` | '_ \| | | / __|  _____    | | | | | || | 
    #     | |_| |  _ <| |  | | (_) | (_| | |_) | |_| \__ \ |_____|   | | | |_| || | 
    #      \___/|_| \_\_|  |_|\___/ \__,_|_.__/ \__,_|___/           |_|  \___/|___|
    #                                                                               
    # --------------------------------------------------------------------------------- """
    LOGO: str = r"""#      _   _ ____  __  __           _ _                         _____ _   _ ___ 
#     | | | |  _ \|  \/  | ___   __| | |__  _   _ ___          |_   _| | | |_ _|
#     | | | | |_) | |\/| |/ _ \ / _` | '_ \| | | / __|  _____    | | | | | || | 
#     | |_| |  _ <| |  | | (_) | (_| | |_) | |_| \__ \ |_____|   | | | |_| || | 
#      \___/|_| \_\_|  |_|\___/ \__,_|_.__/ \__,_|___/           |_|  \___/|___|
#                                                                               
# --------------------------------------------------------------------------------- """

    @staticmethod
    def updateSetting(setting:str,value)->tuple[bool,str]:
        """This function changes values in the config

        Args:
            setting (str): the setting requiring changes.
            value : the new value

        Returns:
            tuple[bool,str]: succes or not and the message
        """
            

        if not hasattr(Settings,setting) or callable(getattr(Settings, setting)):
                return 0,f"{setting} doesnt appear to be modifiable"
        
        
        # Since we assume all inputs are strings, we must check if the string can represent the target type.
        target_attr = getattr(Settings, setting)
        current_type = type(target_attr)

        try:
            if current_type == str:
                # If expected type is string, just assign the string value (which we assume it is).
                setattr(Settings, setting, str(value))
                return True,f"New value for {setting}: {value}"
            elif current_type == int:
                # Check if the string can be safely converted to an integer.
                try:
                    int(value)
                    setattr(Settings, setting, int(value))
                    return True,f"New value for {setting}: {value}"
                except ValueError:
                    return False,f"Conversion failed"
            elif current_type == float:
                # Check if the string can be safely converted to a float.
                try:
                    float(value) # Test conversion first
                    setattr(Settings, setting, float(value))
                    return True,f"New value for {setting}: {value}"
                except ValueError:
                    return False,f"Conversion failed"
            elif current_type == bool:
                # Boolean handling from string is ambiguous ("true", "1", "yes").
                # For simplicity based on the prompt's constraint (assuming str input), we might reject it or enforce specific strings.
                # Here, we will only accept "True" or "False" case-insensitively for safety.
                if value.lower() in ('true', '1'):
                    setattr(Settings, setting, True)
                    return True,f"New value for {setting}: {value}"
                elif value.lower() in ('false', '0'):
                    setattr(Settings, setting, False)
                    return True,f"New value for {setting}: {value}"
                else:
                    return False,f"Conversion failed"
                # For other types (like complex dicts or lists), we rely on direct string assignment if the structure is simple enough,
                # but given the strict requirement to assume str input, we'll treat it as a failure unless explicitly handled.
            else:
                # Fallback for unhandled types (e.g., tuple in MOTS) - attempt conversion only if possible.
                try:
                    if current_type == dict and isinstance(value, str):
                    # If the target is a dict, we cannot reliably convert an arbitrary string to it without more context.
                        return False,f"Type not supported"
                    setattr(Settings, setting, value) # Direct assignment as last resort
                    return True,f"New value for {setting}: {value}"
                except Exception:
                    return False,f"Conversion failed"

        except Exception as e:
            print(f"An unexpected error occurred during updateSetting for {setting}: {e}")
            return False,f"Conversion failed"





