"""This script contains tools to manipulate data

Functions:
    read_data_file: Reads a YAML file and returns its contents as a dictionary.
    build_sequence: Builds a sequence of integers based on the data provided.
    write_task_time: Writes task time to a file.
    calculate_mean_time: Calculates statistical values for a process task file.
    
"""
from URModbus.core.ProcessTools import Process
from URModbus.config.constants import Settings
import yaml
import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt



def read_data_file(file:str)->dict:
    """This function read the data contained in the yaml process file

    Args:
        file (str): name of the file in the DATA_DIR

    Returns:
        dict: the file data
    """
    # Open the YAML file for reading
    with open(f"./{Settings.DATA_DIR}/{file}", 'r') as stream:
        try:
            # Load the data from the YAML file into a Python dictionary
            data = yaml.safe_load(stream)
            return data
        except yaml.YAMLError as exc:
            return exc
        
def build_sequence(data:dict)->list[int]:
    """This function load the sequence from the extracted process file data

    Args:
        data (dict): data extracted with read_data_file

    Returns:
        list[int]: sequence like [1,2,3,4]
    """
    # Extract the ordering list

    sequence = data['ordering']

    # print("Sequence")

    # for task in sequence:
    #     print(f"{(task,data['tasks'][task]['name'])},")


    return sequence
        
def write_task_time(process:str,task:int,dataID:float,time:float):
    """Function to write process times to a file

    Args:
        process (str): the name of the current process, used for directory
        task (int): int of the task
        dataID (float): identifier for the data
        time (float): time of the task
    """
    # Check if the directory exists
    dir_path = f"./{Settings.AUTOGEN_DIR}/{process}"
    if not os.path.exists(dir_path):
        # Create the directory
        os.makedirs(dir_path)

    file_path = dir_path + f"/{task}.txt"
    if not os.path.exists(file_path):
        with open(file_path, 'w') as f:
            pass
    
    with open(file_path, "a") as f:
        f.write(f"{dataID};{time}\n")

def calculate_mean_time(process:str,task:int)->list[float]:
    """Calculates statistical values for a process task file.
    
    Calculates:
     - Mean
     - Standard Deviation
     - Mean +/- Standard Deviation
     - Last 100 values mean

    Args:
        process (str): name of the process
        task (int): number of the file

    Returns:
        list[float]: returns a list of floats [Means, Std Dev, Mean +/- Std dev, Last 100 values mean]
    """
  

    # Read the file
    try:
        data = np.loadtxt(f"./{Settings.AUTOGEN_DIR}/{process}/{task}.txt", delimiter=';')
    except FileNotFoundError:
        return [0]*4
    
    try:
        values = data[:,1]
    except:
        return [0]*4
    
    # Get the last 100 values
    last_100 = data[-100:, 1]

    # Calculate mean, standard deviation, and mean with values in +/- std dev compared to mean
    mean = np.mean(values)
    std_dev = np.std(values)
    within_std_dev = values[(values >= (mean - std_dev)) & (values <= (mean + std_dev))]
    mean_within_std_dev = np.mean(within_std_dev)
    last_100_mean = np.mean(last_100)

    # Return the calculated values
    return [np.round(mean, 2), np.round(std_dev, 2), np.round(mean_within_std_dev, 2), np.round(last_100_mean, 2)]


# ==============================
# CONFIGURATION
# ==============================
def create_gantt_data(process:Process, tasks: list[int]=[])->dict:
    """This function creates the data required to plot the gantt

    Args:
        process (Process): Process to be ploted
        tasks (list[int], optional): tasks to plot, by default all. Defaults to [].

    Returns:
        dict: dictionnary of data {"id": int, "name": str, "duration": float}
    """

    #Extract tasks data from the process
    if tasks == []:
        tasks = process.ordering
    name = process.name

    gantt_data = []
    for task_id in tasks:

        gantt_data.append({
            "id": task_id,
            "name": process.get_task(task_id).name,
            "duration": calculate_mean_time(name,task_id)[0]
        })
    return gantt_data

def plot_gantt(process:Process, tasks: list[int]=[], plotName:str="")->str:
    """Function to plot a Gantt of the process

    Args:
        process (Process): Process to be ploted
        tasks (list[int], optional): list of tsaks to plot. [] for all. Defaults to [].
        plotName (str, optional): Name of the plot, empty for autogenerated. Defaults to "".

    Returns:
        str: name of the created figure
    """

    gantt_data = create_gantt_data(process, tasks)

    current_time = 0.0
    for task in gantt_data:
        task["start"] = current_time
        task["end"] = current_time + task["duration"]
        current_time = task["end"]

    total_time = current_time


    fig, ax = plt.subplots(figsize=(16, 8))

    for i, task in enumerate(gantt_data):
        # Task bar
        ax.barh(
            y=i,
            width=task["duration"],
            left=task["start"],
            height=0.55,
            edgecolor='black',  # Add black border
            color='purple' if i % 2 == 0 else 'orange', # Set color based on index parity
            linewidth=1.0          # Set border width
        )

        #task text
        ax.text(
            task["start"]*0.99,          # a little left of x=0
            i,
            task["name"],
            va="center",
            ha="right",
            fontsize=9,
            color="black"
        )

        ax.axvline(
            task["start"],
            color="blue",
            linestyle=":",
            linewidth=0.8,
            alpha=0.2
        )

        ax.axvline(
            task["end"],
            color="blue",
            linestyle=":",
            linewidth=0.8,
            alpha=0.2
        )

        # Task duration text
        ax.text(
            task["end"] + total_time * 0.01,
            i,
            f"{task['duration']:.2f} s",
            va="center",
            fontsize=9
        )

    # ==============================
    # TOTAL PROCESS TIME (SEPARATE ROW)
    # ==============================
    total_y = len(gantt_data)

    ax.text(
        total_time,
        total_y,
        f"TOTAL: {total_time:.2f} s",
        va="center",
        ha="right",
        fontsize=11,
        fontweight="bold"
    )

    # ==============================
    # AXES & STYLE
    # ==============================
    ax.set_yticks([])                      # remove y ticks and labels
    ax.spines["left"].set_visible(False)  # optional, cleaner look

    ax.set_ylim(-1, total_y + 1)  # space for TOTAL row

    ax.set_xticks([])                      # remove y ticks and labels
    ax.spines["bottom"].set_visible(False)  # optional, cleaner look

    if plotName != "":
        pass
    elif tasks == []:
        plotName = f"Gantt - {process.name} - full"
    elif tasks != []:
        plotName = f"Gantt - {process.name} - partial"
    

    ax.set_title(plotName)

    ax.invert_yaxis()
    ax.grid(axis="x", linestyle="--", alpha=0.4)

    plt.tight_layout()
    
    plt.savefig(f"./{Settings.AUTOGEN_DIR}/{process.name}/{process.name}.png")
    return f"Saved as {process.name}.png in ./{Settings.AUTOGEN_DIR}/{process.name}. Location: ./{Settings.AUTOGEN_DIR}/{process.name}/{process.name}.png"


def cli_gantt(process, tasks: list[int] = [], plotName: str = "") -> list:
    """
    Render a Gantt chart in the CLI with fixed column alignment.

    Args:
        process (Process): Process to be plotted
        tasks (list[int], optional): list of tasks to plot. [] for all
        plotName (str, optional): Name of the plot

    Returns:
        list[str]: Lines to render in CLI
    """

    gantt_data = create_gantt_data(process, tasks)

    # ------------------------------------------------------------------
    # Compute absolute start / end times
    # ------------------------------------------------------------------
    current_time = 0.0
    for task in gantt_data:
        task["start"] = current_time
        task["end"] = current_time + task["duration"]
        current_time = task["end"]

    total_time = current_time

    # ------------------------------------------------------------------
    # Layout constants (fixed-width columns)
    # ------------------------------------------------------------------
    NAME_WIDTH = 20
    BAR_WIDTH = 70      # actual Gantt area
    SEP = " | "
    LINE_WIDTH = NAME_WIDTH + len(SEP) + BAR_WIDTH + 24  # incl time column

    # ------------------------------------------------------------------
    # Title handling
    # ------------------------------------------------------------------
    if not plotName:
        if tasks == []:
            plotName = f"Gantt - CLI - {process.name} - full"
        else:
            plotName = f"Gantt - CLI - {process.name} - partial"

    text = []
    text.append("\n" + "=" * LINE_WIDTH)
    text.append(plotName)
    text.append("=" * LINE_WIDTH)

    # ------------------------------------------------------------------
    # Scaling
    # ------------------------------------------------------------------
    if total_time == 0:
        scale_factor = 1.0
    else:
        scale_factor = BAR_WIDTH / total_time

    text.append(f"Time Scale Factor: {scale_factor:.2f} chars/second")
    text.append("-" * LINE_WIDTH)

    # ------------------------------------------------------------------
    # Task rows
    # ------------------------------------------------------------------
    for task in gantt_data:
        name = task["name"]
        start = task["start"]
        duration = task["duration"]
        end = task["end"]

        # Convert time to character positions
        start_char = max(0, int(start * scale_factor))
        duration_chars = max(1, int(duration * scale_factor))

        if start_char > BAR_WIDTH:
            start_char = BAR_WIDTH
        if start_char + duration_chars > BAR_WIDTH:
            duration_chars = BAR_WIDTH - start_char

        # Fixed-width bar area
        bar_area = (
            " " * start_char +
            "█" * duration_chars +
            " " * (BAR_WIDTH - start_char - duration_chars)
        )

        # Left column
        left = f"{name:<{NAME_WIDTH}}{SEP}"

        # Right column (aligned)
        time_marker = f"[{start:>5.1f}-{end:>5.1f}] ({duration:>4.1f}s)"

        text.append(f"{left}{bar_area} {time_marker}")

    # ------------------------------------------------------------------
    # TOTAL row
    # ------------------------------------------------------------------
    total_bar = "█" * BAR_WIDTH
    left = f"{'TOTAL':<{NAME_WIDTH}}{SEP}"
    time_marker = f"[0.0-{total_time:.1f}] ({total_time:.1f}s)"

    text.append(f"{left}{total_bar} {time_marker}")
    text.append("=" * LINE_WIDTH)

    return text

