"""This script contains tools to manipulate data

Functions:
    read_data_file: Reads a YAML file and returns its contents as a dictionary.
    build_sequence: Builds a sequence of integers based on the data provided.
    write_task_time: Writes task time to a file.
    calculate_mean_time: Calculates statistical values for a process task file.
    
"""
from URModbus.core.ProcessTools import Process
from URModbus.config.constants import Settings
import yaml
import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.stats import norm



def read_data_file(file:str)->dict:
    """This function read the data contained in the yaml process file

    Args:
        file (str): name of the file in the DATA_DIR

    Returns:
        dict: the file data
    """
    # Open the YAML file for reading
    with open(f"./{Settings.DATA_DIR}/{file}", 'r') as stream:
        try:
            # Load the data from the YAML file into a Python dictionary
            data = yaml.safe_load(stream)
            return data
        except yaml.YAMLError as exc:
            return exc
        
def build_sequence(data:dict)->list[int]:
    """This function load the sequence from the extracted process file data

    Args:
        data (dict): data extracted with read_data_file

    Returns:
        list[int]: sequence like [1,2,3,4]
    """
    # Extract the ordering list

    sequence = data['ordering']

    # print("Sequence")

    # for task in sequence:
    #     print(f"{(task,data['tasks'][task]['name'])},")


    return sequence
        
def write_task_time(process:str,task:int,dataID:float,time:float):
    """Function to write process times to a file

    Args:
        process (str): the name of the current process, used for directory
        task (int): int of the task
        dataID (float): identifier for the data
        time (float): time of the task
    """
    # Check if the directory exists
    dir_path = f"./{Settings.AUTOGEN_DIR}/{process}"
    if not os.path.exists(dir_path):
        # Create the directory
        os.makedirs(dir_path)

    file_path = dir_path + f"/{task}.txt"
    if not os.path.exists(file_path):
        with open(file_path, 'w') as f:
            pass
    
    with open(file_path, "a") as f:
        f.write(f"{dataID};{time}\n")

def calculate_mean_time(process:str,task:int)->list[float]:
    """Calculates statistical values for a process task file.
    
    Calculates:
     - Mean
     - Standard Deviation
     - Mean +/- Standard Deviation
     - Last 100 values mean

    Args:
        process (str): name of the process
        task (int): number of the file

    Returns:
        list[float]: returns a list of floats [Means, Std Dev, Mean +/- Std dev, Last 100 values mean]
    """
  

    # Read the file
    try:
        data = np.loadtxt(f"./{Settings.AUTOGEN_DIR}/{process}/{task}.txt", delimiter=';')
    except FileNotFoundError:
        return [0]*4
    
    try:
        values = data[:,1]
    except:
        return [0]*4
    
    # Get the last 100 values
    last_100 = data[-100:, 1]

    # Calculate mean, standard deviation, and mean with values in +/- std dev compared to mean
    mean = np.mean(values)
    std_dev = np.std(values)
    within_std_dev = values[(values >= (mean - std_dev)) & (values <= (mean + std_dev))]
    mean_within_std_dev = np.mean(within_std_dev)
    last_100_mean = np.mean(last_100)

    # Return the calculated values
    return [np.round(mean, 2), np.round(std_dev, 2), np.round(mean_within_std_dev, 2), np.round(last_100_mean, 2)]


# ==============================
# CONFIGURATION
# ==============================
def create_gantt_data(process:Process, tasks: list[int]=[])->dict:
    """This function creates the data required to plot the gantt

    Args:
        process (Process): Process to be ploted
        tasks (list[int], optional): tasks to plot, by default all. Defaults to [].

    Returns:
        dict: dictionnary of data {"id": int, "name": str, "duration": float}
    """

    #Extract tasks data from the process
    if tasks == []:
        tasks = process.ordering
    name = process.name

    gantt_data = []
    for task_id in tasks:

        gantt_data.append({
            "id": task_id,
            "name": process.get_task(task_id).name,
            "duration": calculate_mean_time(name,task_id)[0]
        })
    return gantt_data

def plot_gantt(process:Process, tasks: list[int]=[], plotName:str="")->str:
    """Function to plot a Gantt of the process

    Args:
        process (Process): Process to be ploted
        tasks (list[int], optional): list of tsaks to plot. [] for all. Defaults to [].
        plotName (str, optional): Name of the plot, empty for autogenerated. Defaults to "".

    Returns:
        str: name of the created figure
    """

    gantt_data = create_gantt_data(process, tasks)

    current_time = 0.0
    for task in gantt_data:
        task["start"] = current_time
        task["end"] = current_time + task["duration"]
        current_time = task["end"]

    total_time = current_time


    fig, ax = plt.subplots(figsize=(16, 8))

    for i, task in enumerate(gantt_data):
        # Task bar
        ax.barh(
            y=i,
            width=task["duration"],
            left=task["start"],
            height=0.55,
            edgecolor='black',  # Add black border
            color='purple' if i % 2 == 0 else 'orange', # Set color based on index parity
            linewidth=1.0          # Set border width
        )

        #task text
        ax.text(
            task["start"]*0.99,          # a little left of x=0
            i,
            task["name"],
            va="center",
            ha="right",
            fontsize=9,
            color="black"
        )

        ax.axvline(
            task["start"],
            color="blue",
            linestyle=":",
            linewidth=0.8,
            alpha=0.2
        )

        ax.axvline(
            task["end"],
            color="blue",
            linestyle=":",
            linewidth=0.8,
            alpha=0.2
        )

        # Task duration text
        ax.text(
            task["end"] + total_time * 0.01,
            i,
            f"{task['duration']:.2f} s",
            va="center",
            fontsize=9
        )

    # ==============================
    # TOTAL PROCESS TIME (SEPARATE ROW)
    # ==============================
    total_y = len(gantt_data)

    ax.text(
        total_time,
        total_y,
        f"TOTAL: {total_time:.2f} s",
        va="center",
        ha="right",
        fontsize=11,
        fontweight="bold"
    )

    # ==============================
    # AXES & STYLE
    # ==============================
    ax.set_yticks([])                      # remove y ticks and labels
    ax.spines["left"].set_visible(False)  # optional, cleaner look

    ax.set_ylim(-1, total_y + 1)  # space for TOTAL row

    ax.set_xticks([])                      # remove y ticks and labels
    ax.spines["bottom"].set_visible(False)  # optional, cleaner look

    if plotName != "":
        pass
    elif tasks == []:
        plotName = f"Gantt - {process.name} - full"
    elif tasks != []:
        plotName = f"Gantt - {process.name} - partial"
    

    ax.set_title(plotName)

    ax.invert_yaxis()
    ax.grid(axis="x", linestyle="--", alpha=0.4)

    plt.tight_layout()
    
    plt.savefig(f"./{Settings.AUTOGEN_DIR}/{process.name}/{process.name}.svg")
    return f"Saved as {process.name}.png in ./{Settings.AUTOGEN_DIR}/{process.name}. Location: ./{Settings.AUTOGEN_DIR}/{process.name}/{process.name}.svg"


def cli_gantt(process:Process, tasks: list[int] = [], plotName: str = "", fillcar: str = "█") -> list:
    """
    Render a Gantt chart in the CLI with fixed column alignment.

    Args:
        process (Process): Process to be plotted
        tasks (list[int], optional): list of tasks to plot. [] for all
        plotName (str, optional): Name of the plot
        fillcar (str, optional): Caracter used for representing a cell of time. default to █

    Returns:
        list[str]: Lines to render in CLI
    """

    gantt_data = create_gantt_data(process, tasks)

    # ------------------------------------------------------------------
    # Compute absolute start / end times
    # ------------------------------------------------------------------
    current_time = 0.0
    for task in gantt_data:
        task["start"] = current_time
        task["end"] = current_time + task["duration"]
        current_time = task["end"]

    total_time = current_time

    # ------------------------------------------------------------------
    # Layout constants (fixed-width columns)
    # ------------------------------------------------------------------
    NAME_WIDTH = 20
    BAR_WIDTH = 70      # actual Gantt area
    SEP = " | "
    LINE_WIDTH = NAME_WIDTH + len(SEP) + BAR_WIDTH + 24  # incl time column

    # ------------------------------------------------------------------
    # Title handling
    # ------------------------------------------------------------------
    if not plotName:
        if tasks == []:
            plotName = f"Gantt - CLI - {process.name} - full"
        else:
            plotName = f"Gantt - CLI - {process.name} - partial"

    text = []
    text.append("\n" + "=" * LINE_WIDTH)
    text.append(plotName)
    text.append("=" * LINE_WIDTH)

    # ------------------------------------------------------------------
    # Scaling
    # ------------------------------------------------------------------
    if total_time == 0:
        scale_factor = 1.0
    else:
        scale_factor = BAR_WIDTH / total_time

    text.append(f"Time Scale Factor: {scale_factor:.2f} chars/second")
    text.append("-" * LINE_WIDTH)

    # ------------------------------------------------------------------
    # Task rows
    # ------------------------------------------------------------------
    for task in gantt_data:
        name = task["name"]
        start = task["start"]
        duration = task["duration"]
        end = task["end"]

        # Convert time to character positions
        start_char = max(0, int(start * scale_factor))
        duration_chars = max(1, int(duration * scale_factor))

        if start_char > BAR_WIDTH:
            start_char = BAR_WIDTH
        if start_char + duration_chars > BAR_WIDTH:
            duration_chars = BAR_WIDTH - start_char

        # Fixed-width bar area
        bar_area = (
            " " * start_char +
            fillcar * duration_chars +
            " " * (BAR_WIDTH - start_char - duration_chars)
        )

        # Left column
        left = f"{name:<{NAME_WIDTH}}{SEP}"

        # Right column (aligned)
        time_marker = f"[{start:>5.1f}-{end:>5.1f}] ({duration:>4.1f}s)"

        text.append(f"{left}{bar_area} {time_marker}")

    # ------------------------------------------------------------------
    # TOTAL row
    # ------------------------------------------------------------------
    total_bar = fillcar * BAR_WIDTH
    left = f"{'TOTAL':<{NAME_WIDTH}}{SEP}"
    time_marker = f"[0.0-{total_time:.1f}] ({total_time:.1f}s)"

    text.append(f"{left}{total_bar} {time_marker}")
    text.append("=" * LINE_WIDTH)

    return text

def gaussian(process:Process,task:int,plotName:str = "")->str:
    """This function generates a gaussian chart of a process task, it is similar to gantt creation

    Args:
        process (Process): Process used as a reference
        task (int): Number of the task
        plotName (str, optional): name of the plot. Defaults to "".

    Returns:
        str: name of the saved plot
    """

    #first obtain mean and dev
    mean,dev,_,_ = calculate_mean_time(process.name,task)

    if mean == 0.0 or dev == 0.0:
        return f"Task {task} - {process.get_task(task).name} - hold no exploitable time"

    #Create the time axis from mean+/- 3 dev for >99% of case
    x = np.linspace(mean - 3*dev, mean + 3*dev, 1000)
    
    # Calculate the probability density function (PDF) for the normal distribution
    pdf = norm.pdf(x, loc=mean, scale=dev)
    # Calculate the cumulative distribution function (CDF)
    cdf = norm.cdf(x, loc=mean, scale=dev)

    fig, axes = plt.subplots(2, 1, figsize=(10, 10)) # Create a subplot of 2 figures

    #Handle user redefining the name of the plot
    if plotName != "":
        axes[0].set_title(plotName)
        axes[1].set_title(plotName)
    else:
        axes[0].set_title(f'Task {task} Distribution PDF ({process.name})')
        axes[1].set_title(f'Task {task} Distribution CDF ({process.name})')


    #general settings for axis and grid 
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('Density')
    axes[0].grid(True, linestyle='--', alpha=0.7)

    axes[1].set_xlabel('Time (s)')
    axes[1].set_ylabel('Cumulative Probability')
    axes[1].grid(True, linestyle='--', alpha=0.7)



    # This is used to draw the color zones of the probability rules (68–95–99.7 rule) ---
    zones = [
        (0, 1, 'green', 0.2),
        (1, 2, 'orange', 0.15),
        (2, 3, 'red', 0.1),
    ]

    # This will draw the zones
    for i in [0, 1]:
        for start, end, color, alpha in zones:
            axes[i].axvspan(mean - end*dev, mean - start*dev, color=color, alpha=alpha)
            axes[i].axvspan(mean + start*dev, mean + end*dev, color=color, alpha=alpha)

    # This will draw the vertical lines at special values, mark with red x
    # and add the little text on the graph
    for i in [0, 1]:
        # Plot mean and standard deviation lines
        axes[i].axvline(mean, color='red', linestyle='--', linewidth=1.5)

        # Loop through multiples of standard deviation (n=-3 to n=3)
        for n in [-3, -2, -1, 0, 1, 2, 3]:
            val = mean + n * dev
            axes[i].axvline(val, color='black', linestyle=':', linewidth=1.0)
            
            #Highlight the value
            axes[i].plot(val, 
                         (pdf if i == 0 else cdf)[np.searchsorted(x, val)],
                         color='red',
                         marker='x')

            percent = (pdf if i == 0 else cdf)[np.searchsorted(x, val)]
            # Display the value text next to the vertical line for visualization
            axes[i].text(val + dev/10,
                        np.max(pdf)/2 if i ==0 else 0.5,
                        f'mean {'+' if n >=0 else '-'}{np.abs(n)}σ\n{val:.2f}s\n{(percent*100 if i==1 else percent):.2f}%',
                        va='center',
                        ha='left', 
                        fontsize=8,
                        bbox=dict(boxstyle='round', facecolor='white', alpha=0.85))

    # plot the gaussian curve
    
    for i in [0, 1]:
        
        # This can happen if you have a low mean with high deviation,
        # This is likelly a bad measurment
        if np.min(x)<0:
            # Dashed boundary at x = 0
            axes[i].axvline(0, color='black', linestyle='--', linewidth=1.2)


        #Plot the actual curves
        mask = x < 0
        notmask = x>0
        axes[i].plot(x[mask], (pdf if i == 0 else cdf)[mask],
                    linestyle='dashed', color='blue')
        axes[i].plot(x[notmask], (pdf if i == 0 else cdf)[notmask],
                    linestyle='solid', color='blue')


    #annotations
    text_str = (
        f"Task = {task}\n"
        f"Name = {process.get_task(task).name}\n"
        f"Mean = {mean:.2f}s\n"
        f"Std = {dev:.2f}s\n"
        f"Mean ± Std = [{mean-dev:.2f}s, {mean+dev:.2f}s]"
    )

    for i in [0, 1]:
        axes[i].text(
            0.02, 0.95, text_str,
            transform=axes[i].transAxes,
            fontsize=10,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.85)
        )

    plt.tight_layout() # Adjust layout
    
    plt.savefig(f"./{Settings.AUTOGEN_DIR}/{process.name}/gaussian_{task}.svg")
    return f"Saved as gaussian_{task}.png in ./{Settings.AUTOGEN_DIR}/{process.name}. Location: ./{Settings.AUTOGEN_DIR}/{process.name}/gaussian_{task}.svg"   

